version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_database
    networks:
      - advisenetwork
networks:
  advisenetwork:
